# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('image_url', models.CharField(max_length=300)),
                ('recipe_url', models.CharField(max_length=300)),
                ('ingredients', models.ManyToManyField(to='foodSpyderSite.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodSpyderSite.Recipe')),
            ],
        ),
    ]
